# Dockerfile-mysql — run official MySQL image
FROM mysql:8.0

# The MySQL image uses env vars for initialization:
# MYSQL_ROOT_PASSWORD, MYSQL_DATABASE, MYSQL_USER, MYSQL_PASSWORD
# We do not run extra commands here; Render will pass env vars from render.yaml or dashboard

# Expose default MySQL port
EXPOSE 5432



# MYSQL_HOST     = "dpg-d343daa4d50c73enf9ig-a"
# MYSQL_USER     = "root"
# MYSQL_PASSWORD = "cRkUvjM59t99sAB0iEkUQNp347DlohR6"
# MYSQL_DATABASE = "user_data_d3ik"
# MYSQL_PORT     = 5432
